# Generated by Django 3.0.4 on 2020-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QandaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=150)),
                ('answer', models.TextField(blank=True, default='Poczekaj! Niedługo odpowiem na Twoje pytanie!')),
                ('publish', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
